version: '3'

services:
  mysql:
    image: 'mysql:latest'
    container_name: unicore_mysql
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - "18000:3306"
    environment:
      - MYSQL_DATABASE=douyin
      - MYSQL_USER=douyin
      - MYSQL_PASSWORD=douyin123
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    restart: always
    profiles:
      - dev
      - release

  redis:
    image: redis:7
    container_name: tiktok_redis
    ports:
      - "18003:6379"
    volumes:
      - ./pkg/configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./pkg/data/redis/:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    profiles:
      - dev
      - release

  unicore:
    container_name: unicore-backend
    depends_on:
      - mysql
      - redis
    restart: always
    network_mode: host
    profiles:
      - release

